sudo: required
services:
  - docker

before_install:
  - docker build -t tmrtkbusiness/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true tmrtkbusiness/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-326670118532"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
